### ISSUE TITLE
InvokeCommandAction CommandParameter

### ISSUE THREAD

**Issue by kaki104** [jlaanstra/Windows.UI.Interactivity#5]
hi
Most of all thank you this Interactivity

I using it in my project.

&lt;i:Interaction.Triggers&gt;
    &lt;i:EventTrigger EventName="ItemClick" SourceName="main02GridView"&gt;
        &lt;i:InvokeCommandAction Command="{Binding ItemClickCommand, Mode=OneWay}" 
                                CommandParameter="{Binding ElementName=gridView}"/&gt;
    &lt;/i:EventTrigger&gt;
&lt;/i:Interaction.Triggers&gt;

but, CommandParameter is null return.
if i remove ElementName=gridView, so, CommandParameter is ViewModel return.
how can i get GridView object?

**Comment by jlaanstra** [comment]
This doesn't work because Behaviors and Triggers are attached properties. They therefore do not have access to the visual tree, so they don't have access to the namescope where gridView is defined. A workaround is explained [here](http://julmar.com/blog/mark/?p=237), but in general you should not pass UI elements to your ViewModels.
